-- INSERT BLOCK_API_TB (Without PK)
-- INSERT INTO BLOCK.BLOCK_API_TB(partition_sq, tree_cd, tree_path, tree_level, disp_nm, disp_ord, created_dt, updated_dt, active_fl, enable_fl, writer, editor, `desc`)
-- VALUES (1, 15, "2.6.15", 3, "treeA", 1, NOW(), NOW(), 1, 1, "sdm", "sdm", "");